CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    available   boolean                                 NOT NULL,
    user_id     INTEGER                                 NOT NULL,
    FOREIGN KEY (user_id) references users (id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time timestamp without time zone,
    end_time   timestamp without time zone,
    booker_id  INTEGER                                 NOT NULL,
    item_id    INTEGER                                 NOT NULL,
    status     VARCHAR(255),
    FOREIGN KEY (booker_id) references users (id),
    FOREIGN KEY (item_id) references items (id),
    CONSTRAINT pk_bookers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(255),
    item_id INTEGER                                 NOT NULL,
    user_id INTEGER                                 NOT NULL,
    created timestamp without time zone,
    FOREIGN KEY (user_id) references users (id),
    FOREIGN KEY (item_id) references items (id),
    CONSTRAINT pk_comments PRIMARY KEY (id)
);







